INSERT INTO ep2.virus VALUES
	('COVID-19', 'UGUAGUCAGGAGGAGCGGGCGGCUGGUAUAGAAGGCCAGCACUAGUUAGAUACUCAGUGCAGUAGCCACGGACUGAUUGUUAUUGGGAGUUAUAUCGGAU'),
	('Dengue', 'GGGACCACGGUUUAUCCACAUCCGGUGGAUAACGUGGGCGGAUUAGUCUGUUGUGCGACAGCAACGAUAGAGAUAGUUAACCACAUCAUCGUAUAUGCGG'),
	('H1N1', 'CGCGUUUGCUGACAGUGAAAAGUUAUCCGUAGAAGUAUACGGAAUAGGGCGCGUUAAACCUAUUUGAAUGAUCCCGCGUCACUCUCUCCAUCUCAAUUCU'),
	('Ebola', 'TCGTGCACATTCGGATACATGGGGCATAGTAGGAGGCCAAGCCTCGTAACCCTGTGCGATGAAGTGTTTTGTTTCCAGGTGACGAAGATCCTCGCGTCAG'),
	('Sars', 'GUUCAUGAGAAGAAUUUUAAUAAAAUUGUAUCAGAUCUAUCGGGCGACCUUCGGGCUGGACAUUUCCAUAUCCACCCAGGGAAAACAAUGAAAGACACCC'),
	('Mers', 'UAAAUUGUCCACACUCGUGAAAUAAGCCUGGGUCGGCUGUAGUGAGCUAGGUAAAAGAACGCAUCCGGAAAUGAAUGUAGUUACCCCGAUGUGAGCCAAU'),
	('Zika', 'GGCCAGACAAUCACGAAACCGCAUUCCGCCCGGUUUUAACACGCUAGAAUUGGAAACCUAAGUCGUCCUGAAACUCUAGGAGGGAAGGGUAGUGAUGCCC');

select * from ep2.virus;
