INSERT INTO ep2.servico VALUES
	(0, 'Esse serviço tem como função inserir exame', 'Inserir Exame'),
	(1, 'Esse serviço tem como função inserir paciente', 'Inserir Paciente'),
	(2, 'Esse serviço tem como função inserir usuário', 'Inserir Usuário'),
	(3, 'Esse serviço tem como função inserir amostra', 'Inserir Amostra'),
	(4, 'Esse serviço tem como função inserir perfil', 'Inserir Perfil'),
	(5, 'Esse serviço tem como função inserir virus', 'Inserir Virus'),
	(6, 'Esse serviço tem como função inserir tutorando', 'Inserir Tutorando'),
	(7, 'Esse serviço tem como função remover exame', 'Remover Exame'),
	(8, 'Esse serviço tem como função remover paciente', 'Remover Paciente'),
	(9, 'Esse serviço tem como função remover usuário', 'Remover Usuário'),
	(10, 'Esse serviço tem como função remover amostra', 'Remover Amostra'),
	(11, 'Esse serviço tem como função remover perfil', 'Remover Perfil'),
	(12, 'Esse serviço tem como função remover virus', 'Remover Virus'),
	(13, 'Esse serviço tem como função remover tutorando', 'Remover Tutorando'),
	(14, 'Esse serviço tem como função visualizar exame', 'Visualizar Exame'),
	(15, 'Esse serviço tem como função visualizar paciente', 'Visualizar Paciente'),
	(16, 'Esse serviço tem como função visualizar usuário', 'Visualizar Usuário'),
	(17, 'Esse serviço tem como função visualizar amostra', 'Visualizar Amostra'),
	(18, 'Esse serviço tem como função visualizar perfil', 'Visualizar Perfil'),
	(19, 'Esse serviço tem como função visualizar virus', 'Visualizar Virus'),
	(20, 'Esse serviço tem como função visualizar tutorando', 'Visualizar Tutorando'),
	(21, 'Esse serviço tem como função alterar exame', 'Alterar Exame'),
	(22, 'Esse serviço tem como função alterar paciente', 'Alterar Paciente'),
	(23, 'Esse serviço tem como função alterar usuário', 'Alterar Usuário'),
	(24, 'Esse serviço tem como função alterar amostra', 'Alterar Amostra'),
	(25, 'Esse serviço tem como função alterar perfil', 'Alterar Perfil'),
	(26, 'Esse serviço tem como função alterar virus', 'Alterar Virus'),
	(27, 'Esse serviço tem como função alterar tutorando', 'Alterar Tutorando');

select * from ep2.servico;
